### ISSUE TITLE
Rebranding?

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/slush-es6#12]
Should we rebrand slush-es6 now that ECMAScript 6th edition has been renamed to ECMAScript 2015?

Some positive and negative ideas:

- es-2015 would look outdated too fast, so no.
- "es.next" is too damn overused all over the place, it is too generic so no.
- Perhaps "es20xx" or "es-20xx", then a JS logo with classic mega man would be quite suitable hahah.

Perhaps we can use some ideas from 6to5/6to5#596 / 6to5/6to5#568

@jaydson any ideas?

**Comment by UltCombo** [comment]
Guess I had too much free time so:

![0 0 2 fw](https://cloud.githubusercontent.com/assets/2090712/5991273/cdc76254-a9c9-11e4-801e-ac7063767d84.png)
![0 0 4 fw](https://cloud.githubusercontent.com/assets/2090712/5991274/cfb647e2-a9c9-11e4-98f1-0ff23cd37e94.png)

(I believe using a single sprite falls under fair use, and Capcom people usually isn't an ass regarding this)

I can't seem to find a good font to replace "JS" with "ES" though.

**Comment by UltCombo** [comment]
Okay I should probably stop wasting time and get back to code.

Anyway, should we change the slush-es6 branding to something else? I believe this is the last step before publishing a stable release.

**Comment by UltCombo** [comment]
More suggestions:

- npm package name: `slush-es20xx`; generator command: `slush es20xx`
- npm package name: `slush-es-20xx`; generator command: `slush es-20xx`

![0 0 7 fw](https://cloud.githubusercontent.com/assets/2090712/5993119/8b060e9e-aa2c-11e4-945b-f42312757b18.png)
![0 0 8 fw](https://cloud.githubusercontent.com/assets/2090712/5993121/8edda310-aa2c-11e4-998a-ca89c98502c6.png)

Not sure, but I feel like I should be on the "20xx" idea. If we have copyright problems in the future, we can as well just remove the sprite and keep the "20xx" as a subtle reference.

**Comment by UltCombo** [comment]
Now with less blurry sprites (got originals and resized using nearest neighbor interpolation), and damn, how I could I forget about the Rush Adapter:

![0 0 9 fw](https://cloud.githubusercontent.com/assets/2090712/5993217/d583fbae-aa2f-11e4-9a8d-cb5bb43b30f7.png)

**Comment by UltCombo** [comment]
Btw, all images posted above are Adobe Fireworks PNGs in case anyone want to work on them.

**Comment by UltCombo** [comment]
Now with not only the "20xx" reference, but also the Rush Adapter representing code transformation and improvement, I'm certain that MM7 will be the mascot for `slush-es20xx`.

**Comment by jaydson** [comment]
Sorry for let you speaking with yourself :cry: 
I just loved the "es20xx" idea.
Perhaps we can use try something like this on ES6Rocks.com ? 
Let's think about it.

**Comment by UltCombo** [comment]
Hahah no problem. I like discussing with myself sometimes.
As for the ES6Rocks.com branding, we can bring it up in the [appropriate issue](https://github.com/es6rocks/es6rocks.github.io/issues/49), yes.
