### ISSUE TITLE
`gulp build`: when gulp-jscs fails, its error message is unreadable in Windows command prompt

### ISSUE THREAD

**Issue by UltCombo** [es6rocks/slush-es6#4]
The issue seems to be specific to Windows.

Steps to reproduce:

1. Use the (currently experimental) `gulpfile` branch
1. Create a new project
1. Edit a `.js` file in order for jscs to fail 
1. Run `gulp build`

gulp-jscs's error message in Windows 7's `cmd.exe` only has line breaks visible:
![image](https://cloud.githubusercontent.com/assets/2090712/5531518/e646b3d2-8a13-11e4-8f10-b594a5004ce4.png)

However, actually, it looks like the issue is with gulp-jscs's coloring -- if one copies/inspects the actual stdout contents, the correct error message is there.

The same bug also appears in Git Bash:

![image](https://cloud.githubusercontent.com/assets/2090712/5531555/482073ea-8a14-11e4-82f9-b4fee925520b.png)

The error message is at least visible in Console2 (albeit the coloring is not applied):

![image](https://cloud.githubusercontent.com/assets/2090712/5531564/71ae3a94-8a14-11e4-95eb-06baa78dba06.png)

Noting again: the issue is apparently specific to Windows; The error message is correctly colored in OS X 10.10's zsh.

**Comment by btormey** [comment]
Noticing this issue again on Windows 10 
![capture](https://cloud.githubusercontent.com/assets/5632887/9103044/9746ae02-3bc7-11e5-8c2e-cad136072131.PNG)

**Comment by UltCombo** [comment]
@btormey are you using the version 2.0.3? I'm pretty sure it was fixed in this version.

The next version will be a major release that replaces JSHint and JSCS with ESLint, though I'm currently pondering whether to add JSCS back now that it is [able to lint all valid Babel code](https://github.com/jscs-dev/babel-jscs). By that point we should also have the ability to [disable plugins via `build.js`](https://github.com/JSRocksHQ/slush-es20xx/issues/13), so you can use just what you want.

**Comment by btormey** [comment]
@UltCombo  Ah, that is the issue, I've got 2.0.0 installed. Sorry, it's late here.

**Comment by UltCombo** [comment]
No problem, glad to help. :smile:
